# Generated by Django 4.0 on 2022-02-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Name')),
                ('password', models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Heslo')),
                ('status', models.CharField(choices=[('U', 'Unverified'), ('V', 'Verified'), ('R', 'Restricted')], default='U', max_length=10, verbose_name='Status')),
            ],
        ),
    ]
