# Generated by Django 4.0 on 2022-02-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_crew_user_created_at_user_modified_at_knight'),
    ]

    operations = [
        migrations.AddField(
            model_name='knight',
            name='upload',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
    ]
