# Generated by Django 4.0 on 2022-02-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_knight_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knight',
            name='upload',
        ),
        migrations.AddField(
            model_name='crew',
            name='upload',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/', verbose_name='Crest'),
        ),
    ]
