# Generated by Django 4.0 on 2022-02-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_knight_upload_crew_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
