# Generated by Django 4.0 on 2022-02-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_crew_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knight',
            name='name',
        ),
        migrations.AddField(
            model_name='knight',
            name='first_name',
            field=models.CharField(default='test', max_length=100, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knight',
            name='last_name',
            field=models.CharField(default='stet', max_length=100, verbose_name='Last Name'),
            preserve_default=False,
        ),
    ]
